version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "banco_pix"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql